id: PBF204844
initial_creation_type: input
source_metadata:
  title: Termas
  language: zh
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    8ed256a2d1c34bcf9eb1733bdec00cef:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    fdba9d68343d4ca383a2b5a37533dc7e:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    cdd46285b8c04547b694dc0f34adc936:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    611831a551c1406cb31ac1f257eebda3:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    92a1f0e2f58f4e2cbaaed7c6be031593:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    ddb73cab05c24ba6802f4413780fc057:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    2f0477214ed04d68974846cf480c1735:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    2e27205827f24cfea95cd41c493a393d:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    88128e8367d44c1b8662c3a54852c5aa:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    ae945733c4034091a2fd57cb0b974fd6:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    8144708698584949a4c026f1a84c32d3:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    abb0f8d072254a21b82cc6495b0d4a83:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    529f40e3c4e04e32999fc62a1c1ef44b:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    c4c58e7c042b41e8ac8ce6393807ac47:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    01a15109763942e482ed1405e16fed26:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    1e9d4b15eb254123a7d3a8beed26167e:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    28ab651a600b442eb212064ca2977adf:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    fdb164e692c343c69cfab3bd85952aa3:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    6bf11d90d6b74b63a23d850192939eb0:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    2ced1fb1afde4bd19e0463506da7e60e:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    81ebfa46c6894c4faa8f7dd609b5c45b:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    727de067fa074f6d9b3d0a064d992396:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    cbef5a72503941b7acbd2574e26a96bd:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    c4b4c3a86f9b4644b6cfd6d034731c18:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    b618803b9be84e56997dc045f7fae993:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    938f190c86cd4cacb0129159a2291198:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    c0fb0f680d1d4ced839ecde618907902:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    7381b0c55f854f6b8406d202e3f63ce3:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    aebaa94248c64eb185325314499787fd:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    3e7a2a129cdf4db7a44147c0b06f8d36:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    ecd7cbe0a91b458aa8cf287ab44e7ce2:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    3b3d0e225f184d2c8bacf0e0e247da45:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    bedbb408ee6c45c09d40877ef3991c50:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    c87be8ff80fe477eb35244ce246f293c:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    78fcf3f3e58d4ab1a95ba92103c7ec50:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    27d7880f2b024c309ee3fe7102865ed2:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    e3823c1fb95944d8982aeaa99a1bf1f0:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    800532caff644566b3958752d0f1a7c7:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    047b3da565da4edea91be41bb95177de:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    9b1c4e39fa7a483cb3e820c5eb1a7851:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    4214d93c49c2446584dfe174213c01e7:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    592182b8076e4434802e1b878ab05428:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    c64dd772380b4bd1aa2577e7f393edcb:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    f69670d5bd1c42ac9fbc88715e01b14c:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    d49f9ab35f5241bc8a0f85e245c64023:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    cde1088cff8d455f9e7b8c9b036d0ae8:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    0154653a999f4974a3d14f1dbab3f30d:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    595af9a50851478487130e9135903367:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    8969573d5342418a90b8e83a0992bea5:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    c8d16897eb064e4f8147b7da1e024736:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    daded7fd25f845948cce5597aef2ad4f:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    aee6d121f1054e188cdc549b93e3ce51:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    9377f0266e5448ebbb81c29ec94070fd:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    3620253cfd874a179022c5d587f12783:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    fc8af31eaae84987ba53f0f64c79a936:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    708c2095e8b74c42bd1d0469ef76f00b:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    da925e6cc05c4344b3554f42cc96debe:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    e4d2051d6ba74132a2af9c2249cc2d4b:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    5f217926014348f986780d10cf3483ea:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    12521ae9348c4e58b62903fbad48dae0:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    a57be97399a442ff9fdfc0526306323f:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    26f56e7658784f898d752c6db40bf6b0:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    cfa3466a6bac4a16ae1ea8f89e780da5:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    4faf1ca1a3274690a271034063319a7c:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    4756c891dc7447a1a6020424e0442dc4:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    bab13dbaee344a84b82930992a94748f:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    f636a3b32c0d45f680b1efc01415405e:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    411f0ef8df624a8c86294b2869456954:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    4dfa6f251e5843b89754c008ce68033a:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    7cc3ee0c0e76498aa3d2320dac2a0157:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    c3b792e6e5a24b068a305cbbede97a15:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    e450c6e78a844c9a8ab995d0f2e96b30:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    6fde17c2df53481688c740df2a6c8a66:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    ed1433897a4b46e9ba4ed6767c00886f:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    35885a89cd3040d6a966af75434498a1:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    08f225cac29047928db134e351d45f4d:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    3321aaab95fa4501b95b81d3913f67d1:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    e355f17e10824ff39ea00809e0005af4:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    4474c9127f75430b92d5cf76bd5731a2:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    085feaf6aea44d449c7485f5514a5a16:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    cb6b5cf4cddf44bbaa5285813a72af71:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    c97b5910380749b882bd3875b9666aa4:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    fc3360dd829247d78ab20c3cfae792f8:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    11e24fd7f7cd460b8be133f2c19d729d:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    a13e5bd94ad84db1825936fc0a19b713:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    cf97b94a1c864f4993264be71bd1508d:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    fa7aa7548f274593a0c65a6a87c85dfa:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    829c91071a324ea586b6af55fe35b8bb:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    4c663fecfc094da888de1310e09c0c8c:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    2ab2aad84da04c2f8cb63682cae891aa:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    a621df20a3954f2d8ecefb261e18c866:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    4ca6ad4c833b4856a08debc39727d158:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    a061ff9a500f46db8d746554de4f4cca:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    6202f83cff544b4b860d127181c5a21b:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    703655ed71e64089895e91c7ef3d127a:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    d8fc15d4128940a6a4e97dfb5d6682f8:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    273afb665975444a9075d6095b2fe105:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    4cc94782c0d7445788d707d31aeb36c5:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    d53adb4c25af4e28871f32c2185f3788:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    49abe383fa804583ac351392aa90cc43:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.640890'
last_modified_at: '2022-03-01T06:17:48.640893'
